package com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-07-30T14:19:03.632+02:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://sei.ws.fast.cdc.com/", name = "DocumentService")
@XmlSeeAlso({ObjectFactory.class})
public interface DocumentService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "download", targetNamespace = "http://sei.ws.fast.cdc.com/", className = "com.Download")
    @WebMethod
    @ResponseWrapper(localName = "downloadResponse", targetNamespace = "http://sei.ws.fast.cdc.com/", className = "com.DownloadResponse")
    public com.DocumentContentVO download(
        @WebParam(name = "documentId", targetNamespace = "")
        java.lang.String documentId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "uploadMeta", targetNamespace = "http://sei.ws.fast.cdc.com/", className = "com.UploadMeta")
    @WebMethod
    @ResponseWrapper(localName = "uploadMetaResponse", targetNamespace = "http://sei.ws.fast.cdc.com/", className = "com.UploadMetaResponse")
    public java.lang.String uploadMeta(
        @WebParam(name = "documentId", targetNamespace = "")
        java.lang.String documentId,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "upload", targetNamespace = "http://sei.ws.fast.cdc.com/", className = "com.Upload")
    @WebMethod
    @ResponseWrapper(localName = "uploadResponse", targetNamespace = "http://sei.ws.fast.cdc.com/", className = "com.UploadResponse")
    public java.lang.String upload(
        @WebParam(name = "label", targetNamespace = "")
        java.lang.String label,
        @WebParam(name = "comment", targetNamespace = "")
        java.lang.String comment,
        @WebParam(name = "subscriberId", targetNamespace = "")
        java.lang.String subscriberId,
        @WebParam(name = "circuitId", targetNamespace = "")
        java.lang.String circuitId,
        @WebParam(name = "dataFileVO", targetNamespace = "")
        com.DataFileVO dataFileVO
    );

    @RequestWrapper(localName = "delete", targetNamespace = "http://sei.ws.fast.cdc.com/", className = "com.Delete")
    @WebMethod
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://sei.ws.fast.cdc.com/", className = "com.DeleteResponse")
    public void delete(
        @WebParam(name = "documentId", targetNamespace = "")
        java.lang.String documentId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sign", targetNamespace = "http://sei.ws.fast.cdc.com/", className = "com.Sign")
    @WebMethod
    @ResponseWrapper(localName = "signResponse", targetNamespace = "http://sei.ws.fast.cdc.com/", className = "com.SignResponse")
    public boolean sign(
        @WebParam(name = "documentId", targetNamespace = "")
        java.lang.String documentId,
        @WebParam(name = "pin", targetNamespace = "")
        java.lang.String pin
    );
}
